### ISSUE TITLE
fix pylint errors in the upstream

### ISSUE THREAD

**Issue by justadreamer** [postindustria-tech/device-detection-python#3]
# Background

In the upstream repository [51degrees:pipeline-python](https://github.com/51Degrees/device-detection-python) - the most build and test runs [fail](https://github.com/51Degrees/device-detection-python/actions/runs/6387808072/job/17344836753#step:5:618) due to pylint errors reported

# Objective

Fix the errors found by pylint, so that the build passes. 

# Details

Please make a fix on a separate branch in this repo and submit a PR from it to the upstream:main branch.

**Comment by Sniperik** [comment]
Resolved with [this PR](https://github.com/51Degrees/device-detection-python/pull/36)
