### ISSUE TITLE
Integration tests should test actual package code

### ISSUE THREAD

**Issue by justadreamer** [postindustria-tech/device-detection-python#5]
# Background
The objective of integration tests running as part of `Nightly Publish Main` workflow is to test the actual packages we are to ship to PyPI, `Nightly PRs to Main` tests should test packages as local dev dependencies.

The Build step of the https://github.com/51Degrees/common-ci/blob/main/.github/workflows/nightly-publish-main.yml workflow should create package artifacts that are to be installed as local pip dependencies and tested. 

We once attempted to make an adjustment that should have tested the actual packages to be shipped, but it failed and we reverted that commit: https://github.com/postindustria-tech/common-ci/commit/c780b883e4ab60fafb9993d4fc051668e98d4f63 - it looks like some tests hardcoded some paths instead of using the packages...

Here are the actions that failed before reverting this commit: 
- https://github.com/51Degrees/device-detection-python/actions/runs/6006824638/job/16291993646#step:5:701
- https://github.com/51Degrees/device-detection-python/actions/runs/6006833206/job/16292420688#step:6:493

# Objective

Make sure the tests are able to actually test the packages to be shipped.  

The packages are built and must be installed as part of the Nightly Publish Main: https://github.com/51Degrees/common-ci/blob/391e344f0c07b19a405ff20bcd84a294b76afba7/nightly-publish-main_package.ps1#L42  prior to testing.  If there is no install step of a built artifact prior to running tests - then we probably will need to add it. 

cc: @pi-alexander-popel

**Comment by Sniperik** [comment]
Resolved in these PRs:
[common-ci](https://github.com/51Degrees/common-ci/pull/52)
[location-python](https://github.com/51Degrees/location-python/pull/8)
[pipeline-python](https://github.com/51Degrees/pipeline-python/pull/15)
[device-detection-python](https://github.com/51Degrees/device-detection-python/pull/38)
